<<<<<<< HEAD
# Site settings
title: Amin Bashi
email: hello@aminbashi.com
description: Hi there # this means to ignore newlines until "baseurl:"
baseurl: "aminbashi.com" # the subpath of your site, e.g. /blog/
url: "aminbashi.com" # the base hostname & protocol for your site

twitter_username: aminbashi
github_username: syde15

# Build settings
markdown: kramdown
=======
theme: jekyll-theme-cayman
>>>>>>> c302d3f0635da752ae16f0f6cb3ab29507c13688
