<<<<<<< HEAD
# Site settings
title: Amin Bashi
email: hello@aminbashi.com
description: Hi there # this means to ignore newlines until "baseurl:"
baseurl: "https://syde15.github.io/" # the subpath of your site, e.g. /blog/
url: "https://syde15.github.io/" # the base hostname & protocol for your site

twitter_username: aminbashi
github_username: syde15

# Build settings
markdown: kramdown
=======
theme: jekyll-theme-cayman
>>>>>>> c302d3f0635da752ae16f0f6cb3ab29507c13688
